name: Unity Tests
on: [ push, pull_request ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: game-ci/unity-test-runner@v2
        with:
          projectPath: .
          testMode: EditMode
      - uses: game-ci/unity-test-runner@v2
        with:
          projectPath: .
          testMode: PlayMode

